version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v0-npm
      - restore_cache:
          keys:
            - v0-mongodb-{{ .Branch }}
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          key: v0-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          key: v0-mongodb-{{ .Branch }}
          paths:
            - $HOME/.mongodb-binaries
